# Generated by Django 5.1.2 on 2024-10-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
