# Generated by Django 5.1.2 on 2024-10-21 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('responsibility', models.TextField()),
                ('experience', models.TextField()),
                ('benfits', models.TextField()),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField()),
                ('website_link', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('experience', models.CharField(choices=[('Jenior', 'Jenior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], default='Jenior', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
