# Generated by Django 5.1.2 on 2024-10-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='application/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='application/'),
        ),
    ]
